[project]
authors = ["gerald-scharitzer <gerald.scharitzer@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max", "gerald-scharitzer"]
description = "Add a short description here"
name = "mopro"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=24.5.0,<25"
tephrite = ">=0.1.0a0.dev0,<0.2"
